const cars=[
 {id:'zeekr',name:'Zeekr 001',trim:'Long Range · Shooting brake',type:'electric',body:'sedan',year:2024,km:'12 800 км',power:'544 л.с.',fuel:'Электро',price:3890000,image:'assets/zeekr.jpg',tag:'Электрический характер',city:'Шанхай'},
 {id:'li',name:'Li Auto L7',trim:'Max · Семейный кроссовер',type:'hybrid',body:'suv',year:2024,km:'8 400 км',power:'449 л.с.',fuel:'Гибрид',price:4590000,image:'assets/li.jpg',tag:'Место для всего',city:'Гуанчжоу'},
 {id:'xiaomi',name:'Xiaomi SU7',trim:'Max · Спортивный седан',type:'electric',body:'sedan',year:2024,km:'6 200 км',power:'673 л.с.',fuel:'Электро',price:4190000,image:'assets/xiaomi.jpg',tag:'Новый взгляд на движение',city:'Шанхай'}
];
let saved;try{saved=new Set(JSON.parse(localStorage.getItem('potok-saved')||'[]'))}catch{saved=new Set()}
let filter='all',view='all';const feed=document.querySelector('#feed');const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
function notify(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function render(){const list=cars.filter(c=>(view==='all'||saved.has(c.id))&&(filter==='all'||c.type===filter||c.body===filter));document.querySelector('#saved-count').textContent=saved.size;
feed.innerHTML=list.length?list.map(c=>`<article class="car" data-id="${c.id}"><div class="visual"><img src="${c.image}" alt="${c.name}, внешний вид" draggable="false"><div class="badges"><span class="badge">${c.tag}</span><span class="badge dark">CN · ${c.city}</span></div><span class="photo-label">Фото модели</span></div><div class="car-body"><div class="title-row"><div><h3>${c.name}</h3><p class="sub">${c.trim}</p></div><button class="save ${saved.has(c.id)?'is-saved':''}" aria-label="${saved.has(c.id)?'Удалить из избранного':'Сохранить '+c.name}" aria-pressed="${saved.has(c.id)}" data-save="${c.id}">${saved.has(c.id)?'♥':'♡'}</button></div><ul class="specs"><li><b>${c.year}</b><span>Год выпуска</span></li><li><b>${c.km}</b><span>Пробег</span></li><li><b>${c.power}</b><span>Мощность</span></li><li><b>${c.fuel}</b><span>Двигатель</span></li></ul><div class="price-row"><div><div class="price">${money(c.price)}</div><div class="price-note">Пример стоимости с доставкой в РФ</div></div><button class="primary" data-detail="${c.id}">Об автомобиле ↗</button></div></div></article>`).join(''):'<div class="empty"><h2>Пока ни одной машины</h2><p>Сохраните понравившийся автомобиль или выберите другой фильтр.</p><button class="primary" id="reset">Вернуться к ленте</button></div>';
feed.scrollTop=0;updateCount();}
function updateCount(){const items=[...feed.querySelectorAll('.car')];const i=items.length?Math.round(feed.scrollTop/(items[0].offsetHeight+16))+1:0;document.querySelector('#feed-count').textContent=String(Math.min(i,items.length)).padStart(2,'0')+' / '+String(items.length).padStart(2,'0')}
feed.addEventListener('scroll',updateCount,{passive:true});
document.addEventListener('click',e=>{const s=e.target.closest('[data-save]'),d=e.target.closest('[data-detail]'),f=e.target.closest('[data-filter]'),v=e.target.closest('[data-view]');if(s){const id=s.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);try{localStorage.setItem('potok-saved',JSON.stringify([...saved]))}catch{}const y=feed.scrollTop;render();feed.scrollTop=y;notify(saved.has(id)?'Автомобиль в избранном':'Автомобиль удалён из избранного')}
if(f){filter=f.dataset.filter;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('selected',x===f));render()}
if(v){view=v.dataset.view;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x===v));render()}
if(d){const c=cars.find(x=>x.id===d.dataset.detail);document.querySelector('#detail-content').innerHTML=`<span class="eyebrow">ЗНАКОМЬТЕСЬ БЛИЖЕ</span><h2>${c.name}</h2><p>${c.trim}. ${c.year} год, ${c.km}. ${c.fuel}, ${c.power}.</p><h3>Из чего складывается цена</h3><div class="cost-line"><span>Автомобиль в Китае</span><b>${money(c.price-990000)}</b></div><div class="cost-line"><span>Доставка и оформление</span><b>290 000 ₽</b></div><div class="cost-line"><span>Пошлины и сборы</span><b>700 000 ₽</b></div><div class="cost-line total"><span>Примерная стоимость</span><span>${money(c.price)}</span></div><p>Это демонстрационная карточка, а не предложение о продаже. Фото показывает модель; комплектация, пробег и расчёт приведены для примера. Реальная цена требует проверки автомобиля и актуального расчёта.</p>`;document.querySelector('dialog').showModal()}
if(e.target.closest('.close'))document.querySelector('dialog').close();if(e.target.id==='reset'){filter='all';view='all';document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('selected',x.dataset.filter==='all'));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view==='all'));render()}});
document.addEventListener('keydown',e=>{if(document.querySelector('dialog').open||!['ArrowDown','ArrowUp'].includes(e.key))return;e.preventDefault();const card=feed.querySelector('.car');if(card)feed.scrollBy({top:(card.offsetHeight+16)*(e.key==='ArrowDown'?1:-1),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})});
render();
